spring:
  application:
    name: vehicles-api
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:mem:dogdata"
    driverClassName: "org.h2.Driver"
    username: sa
    password: password

external-services:
  pricing:
    endpoint: http://localhost:9002
  maps:
    endpoint: http://localhost:9003

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    service-url:
      default-zone: http://localhost:9000/eureka/
instance:
  preferIpAddress: true

server:
  port: 9001

