spring:
  application:
    name: vehicles-api
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:mem:dogdata"
    driverClassName: "org.h2.Driver"
    username: sa
    password: password

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    service-url:
      default-zone: http://localhost:8761/eureka/
instance:
  preferIpAddress: true

server:
  port: 9001

